// Shared skill data + platform definitions for the Skill Manager.

(function () {
  const PLATFORMS = [
    // visible
    { id: 'central',   name: 'Central Skills', short: 'Central', path: '~/.skillloom/skills/',       group: 'Core',    visible: true,  isHub: true },
    { id: 'claude',    name: 'Claude Code',    short: 'Claude',  path: '~/.claude/skills/',          group: 'Coding',  visible: true },
    { id: 'codex',     name: 'Codex CLI',      short: 'Codex',   path: '~/.agents/skills/',          group: 'Coding',  visible: true },
    { id: 'openclaw',  name: 'OpenClaw 开爪',   short: 'OpenClaw', path: '~/.openclaw/skills/',        group: 'Lobster', visible: true },
    // hidden by default — toggleable in Settings
    { id: 'cursor',    name: 'Cursor',         short: 'Cursor',  path: '~/.cursor/skills/',          group: 'Coding',  visible: false },
    { id: 'gemini',    name: 'Gemini CLI',     short: 'Gemini',  path: '~/.gemini/skills/',          group: 'Coding',  visible: false },
    { id: 'copilot',   name: 'Copilot',        short: 'Copilot', path: '~/.copilot/skills/',         group: 'Coding',  visible: false },
    { id: 'windsurf',  name: 'Windsurf',       short: 'Windsurf',path: '~/.windsurf/skills/',        group: 'Coding',  visible: false },
    { id: 'aider',     name: 'Aider',          short: 'Aider',   path: '~/.aider/skills/',           group: 'Coding',  visible: false },
    { id: 'qclaw',     name: 'QClaw 千爪',      short: 'QClaw',   path: '~/.qclaw/skills/',           group: 'Lobster', visible: false },
    { id: 'easyclaw',  name: 'EasyClaw 简爪',   short: 'EasyClaw',path: '~/.easyclaw/skills/',        group: 'Lobster', visible: false },
    { id: 'workbuddy', name: 'WorkBuddy 打工搭子', short: 'WorkBuddy', path: '~/.workbuddy/skills-marketplace/skills/', group: 'Lobster', visible: false },
  ];

  const SKILLS = [
    {
      id: 'pdf-extract',
      title: 'pdf-extract',
      tagline: 'Pull text, tables, and images out of any PDF',
      ai: 'Reads a PDF and returns clean, structured Markdown. Handles multi-column layouts, scanned pages (via OCR), and merged-cell tables. Best for research papers, financial reports, and contract review.',
      version: '1.4.2',
      size: '48 KB',
      files: 3,
      updated: '2 days ago',
      tags: ['document', 'extraction', 'ocr'],
      routes: ['central', 'claude', 'codex'],
    },
    {
      id: 'screenshot-annotate',
      title: 'screenshot-annotate',
      tagline: 'Arrows, highlights, captions for screenshots',
      ai: 'Drop in a screenshot and a one-line intent; outputs a marked-up image with callouts. Auto-detects UI elements so arrows snap to button edges. Great for bug reports, tutorials, and feedback loops.',
      version: '0.9.1',
      size: '72 KB',
      files: 5,
      updated: '5 hours ago',
      tags: ['image', 'visual'],
      routes: ['central', 'claude', 'openclaw'],
    },
    {
      id: 'markdown-deck',
      title: 'markdown-deck',
      tagline: 'Turn Markdown into a polished slide deck',
      ai: 'Splits a Markdown document on H1/H2 boundaries, applies a chosen theme, and emits an HTML slide deck with speaker notes. Supports Mermaid diagrams and code highlighting out of the box.',
      version: '2.1.0',
      size: '156 KB',
      files: 12,
      updated: 'yesterday',
      tags: ['presentation', 'markdown'],
      routes: ['central', 'claude'],
    },
    {
      id: 'git-commit',
      title: 'git-commit',
      tagline: 'Conventional commit messages from a diff',
      ai: 'Reads staged changes via `git diff --cached` and proposes 3 conventional-commit candidates with reasoning. Detects breaking changes, infers scope from modified paths, and respects the repo\'s existing tone.',
      version: '1.0.8',
      size: '12 KB',
      files: 2,
      updated: '1 week ago',
      tags: ['git', 'workflow'],
      routes: ['central', 'claude', 'codex', 'openclaw'],
    },
    {
      id: 'api-doc-gen',
      title: 'api-doc-gen',
      tagline: 'OpenAPI docs from typed source code',
      ai: 'Walks TypeScript / Python / Go source, infers route handlers and their schemas, and emits an OpenAPI 3.1 document. Pairs nicely with redoc or swagger-ui for hosted docs.',
      version: '0.6.3',
      size: '92 KB',
      files: 8,
      updated: '3 days ago',
      tags: ['api', 'docs'],
      routes: ['central', 'codex'],
    },
    {
      id: 'sql-formatter',
      title: 'sql-formatter',
      tagline: 'Format and lint SQL with dialect awareness',
      ai: 'Pretty-prints SQL across Postgres, MySQL, BigQuery, and Snowflake dialects. Catches common smells (SELECT *, missing JOIN keys, ambiguous columns) and flags them inline.',
      version: '3.0.1',
      size: '34 KB',
      files: 4,
      updated: '2 weeks ago',
      tags: ['sql', 'lint'],
      routes: ['central', 'claude', 'codex'],
    },
    {
      id: 'react-refactor',
      title: 'react-refactor',
      tagline: 'Modernize class components to hooks',
      ai: 'Converts legacy React class components to function components with hooks, preserving lifecycle semantics. Refuses to touch components with non-trivial getDerivedStateFromProps until you confirm.',
      version: '1.2.0',
      size: '64 KB',
      files: 6,
      updated: '4 days ago',
      tags: ['react', 'refactor'],
      routes: ['central', 'claude'],
    },
    {
      id: 'log-analyzer',
      title: 'log-analyzer',
      tagline: 'Summarize and cluster log streams',
      ai: 'Reads a log file or piped stdin, groups similar lines via embeddings, and surfaces the top error clusters with example lines and frequency over time. Good first stop when triaging a fresh incident.',
      version: '0.4.7',
      size: '88 KB',
      files: 5,
      updated: '6 days ago',
      tags: ['ops', 'logs'],
      routes: ['central', 'codex'],
    },
    {
      id: 'test-scaffold',
      title: 'test-scaffold',
      tagline: 'Generate test files from source',
      ai: 'Scaffolds a test file for the active source file: detects framework (Jest / Vitest / Pytest), proposes test cases for each exported function, and stubs mocks for imported modules.',
      version: '0.8.0',
      size: '40 KB',
      files: 3,
      updated: '1 day ago',
      tags: ['testing'],
      routes: ['central', 'claude', 'codex'],
    },
    {
      id: 'dependency-audit',
      title: 'dependency-audit',
      tagline: 'Audit npm / pip / cargo dependencies',
      ai: 'Combines `npm audit`, OSV, and GitHub Advisory feeds into a single report grouped by severity. Tells you which advisories are actually reachable from your code, not just present in node_modules.',
      version: '1.1.4',
      size: '52 KB',
      files: 4,
      updated: '3 weeks ago',
      tags: ['security', 'deps'],
      routes: ['central', 'openclaw'],
    },
    {
      id: 'regex-builder',
      title: 'regex-builder',
      tagline: 'Build and explain regular expressions',
      ai: 'Give it a few example matches and a few non-matches; it produces a regex with a plain-English explanation of each group. Also goes the other way: paste a regex, get an explanation.',
      version: '0.3.2',
      size: '18 KB',
      files: 2,
      updated: '5 days ago',
      tags: ['regex', 'text'],
      routes: ['central', 'claude', 'codex', 'openclaw'],
    },
    {
      id: 'type-inference',
      title: 'type-inference',
      tagline: 'Infer TypeScript types for JS files',
      ai: 'Reads a JavaScript module and proposes TypeScript signatures for every exported function and object. Respects existing JSDoc annotations. Outputs a .d.ts alongside, or migrates the file in-place.',
      version: '0.5.0',
      size: '26 KB',
      files: 3,
      updated: '4 hours ago',
      tags: ['typescript', 'migration'],
      routes: ['central', 'claude'],
    },
    {
      id: 'icon-generator',
      title: 'icon-generator',
      tagline: 'Generate consistent SVG icon sets',
      ai: 'Given a few seed icons and a style guide, produces a coordinated SVG set with consistent stroke width, corner radius, and grid alignment. Outputs both individual SVGs and a sprite sheet.',
      version: '0.2.1',
      size: '110 KB',
      files: 7,
      updated: '2 weeks ago',
      tags: ['design', 'svg'],
      routes: ['central'],
    },
  ];

  window.SKILL_DATA = { PLATFORMS, SKILLS };
})();
